CREATE OR REPLACE TABLE ECOMMERCE_RAW.STREAMING.RAW_CLICKSTREAM (
    event_data VARIANT,
    metadata_filename STRING,
    metadata_file_row_number INT,
    ingested_at TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE STAGE ECOMMERCE_RAW.STREAMING.S3_CLICKSTREAM_STAGE
    URL = 's3://my-ecommerce-project-landing-zone/click-stream-raw/'
    STORAGE_INTEGRATION = s3_integration -- ชื่อ Integration เดิมที่มึงใช้
    FILE_FORMAT = (TYPE = 'JSON');


CREATE OR REPLACE PIPE ECOMMERCE_RAW.STREAMING.CLICKSTREAM_PIPE
AUTO_INGEST = TRUE
AS
COPY INTO ECOMMERCE_RAW.STREAMING.RAW_CLICKSTREAM (event_data, metadata_filename, metadata_file_row_number)
FROM (
  SELECT 
    $1, 
    METADATA$FILENAME, 
    METADATA$FILE_ROW_NUMBER 
  FROM @ECOMMERCE_RAW.STREAMING.S3_CLICKSTREAM_STAGE
);






SELECT * FROM table(information_schema.copy_history(
   table_name => 'ECOMMERCE_RAW.STREAMING.RAW_CLICKSTREAM', 
   start_time => dateadd(hours, -1, current_timestamp())
));

DESC PIPE ECOMMERCE_RAW.STREAMING.CLICKSTREAM_PIPE;



ALTER PIPE ECOMMERCE_RAW.STREAMING.CLICKSTREAM_PIPE REFRESH;
DESC PIPE ECOMMERCE_RAW.STREAMING.CLICKSTREAM_PIPE;

DESC STORAGE INTEGRATION s3_integration; 



SELECT COUNT(*), MAX(INGESTED_AT) FROM ECOMMERCE_RAW.STREAMING.RAW_CLICKSTREAM;




SELECT * FROM ECOMMERCE_RAW.DBT_ECOMMERCE.FCT_CUSTOMER_JOURNEY;




SELECT DISTINCT user_id FROM ECOMMERCE_RAW.DBT_ECOMMERCE.STG_CLICKSTREAM;



SELECT COUNT(*) FROM ECOMMERCE_RAW.DBT_ECOMMERCE.FCT_CLICKSTREAM_SESSIONS;


SELECT COUNT(*) FROM ECOMMERCE_RAW.DBT_ECOMMERCE.INT_SESSIONIZED_EVENTS;

SELECT count(*) FROM ECOMMERCE_RAW.DBT_ECOMMERCE.FCT_CLICKSTREAM_SESSIONS ;
