SELECT * FROM ECOMMERCE_RAW.DBT_ECOMMERCE.STG_USERS LIMIT 10;

DESCRIBE VIEW ECOMMERCE_RAW.DBT_ECOMMERCE.STG_ORDERS;



SELECT count(*) 
FROM ECOMMERCE_RAW.LANDING.ORDERS o
JOIN ECOMMERCE_RAW.LANDING.USERS u ON o.user_id = u.id;


SELECT DISTINCT user_id FROM ECOMMERCE_RAW.LANDING.ORDERS 
INTERSECT 
SELECT DISTINCT id FROM ECOMMERCE_RAW.LANDING.USERS;


SELECT count(*) FROM ECOMMERCE_RAW.DBT_ECOMMERCE.INT_CUSTOMER_ORDERS ;



SELECT * FROM ECOMMERCE_RAW.DBT_ECOMMERCE.FCT_DAILY_SALES LIMIT 30;



SELECT * FROM ECOMMERCE_RAW.DBT_ECOMMERCE.FCT_REVENUE_PERFORMANCE LIMIT 30;
